apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-web
  name: app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-web
    spec:
      containers:
      - image: nginx:1.21.6
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        # pull policy; IfNotPresent(default) Always Never
        imagePullPolicy: Always
        # restart policy; Always(default) OnFailure Never
        restartPolicy: Always
        resources: 
          required: 
            memory: "64Mi"
            cpu: "1000m"
          limit:
            memory: "128Mi"
            cpu: "2000m"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  type: ClusterId
  creationTimestamp: null
  labels:
    app: app-web
  name: app-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-web
status:
  loadBalancer: {}
